name: Create compiled on Windows
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pyinstaller
      - run: pyinstaller --onefile src\gui_check.py
      - run: dir
      - name: Upload
      - uses: actions/upload-artifact@master
        with:
          name: "gui_check.exe"
          path: "gui_check.exe"
