name: Create compiled on Windows
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pyinstaller
      - run: pyinstaller --onefile src\gui_check.py
      - name: Commit & Push
        uses: actions-x/commit@v2
        with:
            email: iam-py-test@github.com
            name: Update bot
            branch: main
            message: Update the compiled version
