name: Create compiled on Windows
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pyinstaller
      - run: pyinstaller --distpath . --onefile src\gui_check.py
      - run: dir
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: Bot <bot@iam-py-test.github.io>
